#!/bin/bash

#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

thisdir=$(cd "$(dirname "$0")"; pwd)
$thisdir/metadata-check-dependencies || exit 1

if [[ $# -lt 1 ]]
then
    echo "Usage: ${BASH_SOURCE##*/} <properties-file-name.xml>" 1>&2
    exit
fi

schema=$thisdir/metadata_properties.xsd
doc=$1

xmllint --noout --schema $schema $doc || exit 1
python $thisdir/metadata_validate.py $doc || exit 1

