#!/bin/bash
#
# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CMD_LINE_FILE=/data/local/tmp/webview-command-line

if [ $# -eq 0 ] ; then
  # If nothing specified, print the command line (stripping off "webview").
  adb shell "cat $CMD_LINE_FILE 2>/dev/null" | cut -d" " -f "2-"
elif [ $# -eq 1 ] && [ "$1" = '' ] ; then
  # If given an empty string, delete the command line.
  set -x
  adb shell rm $CMD_LINE_FILE >/dev/null
else
  # Else set it.
  set -x
  adb shell "echo 'webview $*' > $CMD_LINE_FILE"
  adb shell chmod 0664 $CMD_LINE_FILE
fi
