<div class="header">
  <div class="logo">
    <a href="http://code.google.com/android/documentation.html"><img style="border: 0;" src="http://code.google.com/android/images/android_icon_125.png"/></a>
  </div>
  <div class="specbox">
    <table>
      <tr>
        <th colspan="2"> API Diff Specification </th>
      </tr>
      <tr>
        <td>To Version:</td> <td>$to_desc$</td>
      </tr>
      <tr>
        <td>From Version:</td> <td>$from_desc$</td>
      </tr>
      <tr>
        <td>Generated</td> <td>$creation_time$</td>
      </tr>
    </table>
  </div>
</div>