LOCAL_SRC_FILES += $(OMAP4_DEBUG_SRC)
LOCAL_SHARED_LIBRARIES += $(OMAP4_DEBUG_SHARED_LIBRARIES)
LOCAL_WHOLE_STATIC_LIBRARIES:= libheaptracker
LOCAL_CFLAGS += $(OMAP4_DEBUG_CFLAGS)
LOCAL_LDFLAGS += $(OMAP4_DEBUG_LDFLAGS)

include $(BUILD_SHARED_LIBRARY)
